notifications:
  email: false

env:
 - CABALVER=1.18 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.2
 - CABALVER=2.2 GHCVER=8.4.2

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update

before_script:
  - wget https://www.stackage.org/lts/cabal.config
  - cabal sandbox init
  - cabal sandbox add-source prometheus-client
  - cabal sandbox add-source prometheus-metrics-ghc
  - cabal sandbox add-source wai-middleware-prometheus

  - cd prometheus-client
  - cabal sandbox init --sandbox ../.cabal-sandbox
  - cabal install --only-dependencies --enable-benchmarks --enable-tests
  - cabal configure --enable-tests

  - cd ../prometheus-metrics-ghc
  - cabal sandbox init --sandbox ../.cabal-sandbox
  - cabal install --only-dependencies --enable-benchmarks --enable-tests
  - cabal configure --enable-tests

  - cd ../wai-middleware-prometheus
  - cabal sandbox init --sandbox ../.cabal-sandbox
  - cabal install --only-dependencies --enable-benchmarks --enable-tests
  - cabal configure --enable-tests

  - cd ../example
  - cabal sandbox init --sandbox ../.cabal-sandbox
  - cabal install --only-dependencies --enable-benchmarks --enable-tests
  - cabal configure --enable-tests

  - cd ..

script:
  - cd prometheus-client && cabal build && cabal test
  - cd ../prometheus-metrics-ghc && cabal build && cabal test
  - cd ../wai-middleware-prometheus && cabal build && cabal test
  - cd ../example && cabal build
